print("1---Python Casting")
print("Specify a Variable Type")
print("There may be times when you want to specify a type on to a variable. This can be done with casting. \nPython is an object-orientated language, and as such it uses classes to define data types, including its primitive types.")
x = int(1)
y = int(2.8)
z = int("3")
print("int(1) : ",x)
print("int(2.8) : ",y)
print("int("3") : ",z)
x = float(1)
y = float(2.8)
z = float("3")
w = float("4.2")
print("float(1) : ",x)
print("float(2.8) : ",y)
print("float("3") : ",z)
print("float("4.2") : ",w)
x = str("s1")
y = str(2)
z = str(3.0)
print("str('s1') : ",x)
print("str(2) : ",y)
print("str(3.0) : ",z)

print("\n2---Python Casting Code Challenge")