print("1---Python Tuples")
mytuple = ("apple", "banana", "cherry")
print("Tuples are used to store multiple items in a single variable.")
thistuple = ("apple", "banana", "cherry")
print(thistuple)
print("*Tuples can also be created without the parentheses:")
thistuple = "apple", "banana", "cherry"
print(thistuple)
print("Tuple items are ordered, unchangeable, and allow duplicate values.")
thistuple = ("apple", "banana", "cherry", "apple", "cherry")
print(thistuple)
thistuple = ("apple", "banana", "cherry")
print("\tlen(thistuple): ",len(thistuple))
thistuple = ("apple",)
print('thistuple = ("apple",)')
print('\ttype(thistuple): ',type(thistuple))
#NOT a tuple
thistuple = ("apple")
print('thistuple = ("apple")')
print('\ttype(thistuple): ',type(thistuple))
thistuple = ()
print(type(thistuple))
tuple1 = ("apple", "banana", "cherry")
tuple2 = (1, 5, 7, 9, 3)
tuple3 = (True, False, False)
print(tuple1)
print(tuple2)
print(tuple3)
tuple1 = ("abc", 34, True, 40, "male")
print(tuple1)
mytuple = ("apple", "banana", "cherry")
print(type(mytuple))
print("The tuple() Constructor")
thistuple = tuple(("apple", "banana", "cherry"))
print(thistuple)

print("\n2---Python - Access Tuple Items")
thistuple = ("apple", "banana", "cherry", "orange", "kiwi", "melon", "mango")
print('thistuple: ',thistuple)
print('\tthistuple[1]: ',thistuple[1])
print("1.Negative Indexing")
print('\tthistuple[-1]: ',thistuple[-1])
print("2.Range of Indexes")
print('\tthistuple[2:5]: ',thistuple[2:5])
print('\tthistuple[:4]: ',thistuple[:4])
print('\tthistuple[2:]: ',thistuple[2:])
print("3.Range of Negative Indexes")
print('\tthistuple[-4,-1]: ',thistuple[-4:-1])
print("4.Check if Item Exists")
thistuple = ("apple", "banana", "cherry")
if "apple" in thistuple:
  print("Yes, 'apple' is in the fruits tuple")

print("\n3---Python - Update Tuples")
print("1.Change Tuple Values")
print("Convert the tuple into a list to be able to change it:")
x = ("apple", "banana", "cherry")
y = list(x)
y[1] = "kiwi"
x = tuple(y)
print(x)
print("2.Add Items")
thistuple = ("apple", "banana", "cherry")
y = list(thistuple)
y.append("orange")
thistuple = tuple(y)
print(thistuple)
thistuple = ("apple", "banana", "cherry")
y = ("orange",)
thistuple += y
print('''y = ("orange",)
thistuple += y''')
print(thistuple)
print("3.Remove Items")
thistuple = ("apple", "banana", "cherry")
y = list(thistuple)
y.remove("apple")
thistuple = tuple(y)
print(thistuple)
thistuple = ("apple", "banana", "cherry")
del thistuple
#print(thistuple) : error

print("\n4---Python - Unpack Tuples")
print('Packing a tuple')
fruits = ("apple", "banana", "cherry")
print(fruits)
print('Unpacking a tuple')
fruits = ("apple", "banana", "cherry")
(green, yellow, red) = fruits
print("(green, yellow, red) = fruits")
print('\tgreen: ',green)
print('\tyellow: ',yellow)
print('\tred: ',red)
print("Using Asterisk*")
fruits = ("apple", "banana", "cherry", "strawberry", "raspberry")
(green, yellow, *red) = fruits
print("(green, yellow, *red) = fruits")
print('\tgreen: ',green)
print('\tyellow: ',yellow)
print('\tred: ',red)
fruits = ("apple", "mango", "papaya", "pineapple", "cherry")
(green, *tropic, red) = fruits
print("(green, *tropic, red) = fruits")
print('\tgreen: ',green)
print('\ttropic: ',tropic)
print('\tred: ',red)

print("\n5---Python - Loop Tuples")
print("1.Loop Through a Tuple")
thistuple = ("apple", "banana", "cherry")
for x in thistuple:
  print(x)
print("2.Loop Through the Index Numbers")
thistuple = ("apple", "banana", "cherry")
for i in range(len(thistuple)):
  print(thistuple[i])
print("3.Using a While Loop")
thistuple = ("apple", "banana", "cherry")
i = 0
while i < len(thistuple):
  print(thistuple[i])
  i = i + 1

print("\n6---Python - Join Tuples")
print("1.Join Two Tuples")
tuple1 = ("a", "b" , "c")
tuple2 = (1, 2, 3)
print("\ttuple1: ",tuple1)
print("\ttuple2: ",tuple2)
tuple3 = tuple1 + tuple2
print('\ttuple3 = tuple1 + tuple2: ',tuple3)
print("2.Multiply Tuples")
fruits = ("apple", "banana", "cherry")
mytuple = fruits * 2
print('\tmytuple = fruits * 2: ',mytuple)

print("\n7---Python - Tuple Methods")
print("Python has two built-in methods that you can use on tuples.")
print("2 methods")

print("\n8---Python - Tuple Exercises")
print("\n9---Python Tuples Code Challenge")